name: chalenge_tractian_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get_it: ^7.7.0
  string_similarity: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/LOGOTRACTIAN.png
  - assets/icons/homeicon.png
  - assets/icons/criticalIcon.png
  - assets/icons/energyIcon.png
  - assets/icons/GoLocation.png
  - assets/icons/component.png
  - assets/icons/asset.png